### ISSUE TITLE
not work XLError('#NAME?')

### ISSUE THREAD

**Issue by SovBur** [aidhound/hotxlfp#2]
Hello. 
The exception ('#NAME?') does not work in the following cases:
`p = hotxlfp.Parser()`
`formula = p.parse("MY_VAR")`
`print(formula['error'])`

expected to get an error '#NAME?', but `None`.

Also:
`formula = p.parse("MY_VAR + 5")`
`print(formula['result'])`

expected to get an result 'None', but `5`.

**Comment by leonelcamara** [comment]
Good catch! I'll fix it.

**Comment by SovBur** [comment]
Thanks
