### ISSUE TITLE
not work XLError

### ISSUE THREAD

**Issue by SovBur** [aidhound/hotxlfp#4]
Hello.
The exception does not work in the following cases:
```
p = hotxlfp.Parser()
formula = p.parse("5:2")
print(formula['error'])
```
expected to get an error, but "None". 

Also:
```
p = hotxlfp.Parser()
formula = p.parse("2(6+2)")
print(formula['error'])
```

**Comment by leonelcamara** [comment]
@SovBur thank you so much for your great bug reports, I would love to know what you're using hotxlfp for.

**Comment by SovBur** [comment]
Thanks for the fixes, I use for web calculator.
