### ISSUE TITLE
not work XLError

### ISSUE THREAD

**Issue by SovBur** [aidhound/hotxlfp#8]
Hello.
The exception does not work in the following cases:
```
p = hotxlfp.Parser()
formula = p.parse("+7 (620) 1574353 / 245")
print(formula['result'], formula['error'])
```
expected to get an error, but "None".

**Comment by leonelcamara** [comment]
I am indeed getting an #ERROR! on formula['error'] are you using the latest version?

**Comment by SovBur** [comment]
I'm sorry, hotxlfp 0.0.9.
Update helped.

**Comment by leonelcamara** [comment]
> Update helped.

Great! Closing the issue then.
