### ISSUE TITLE
ATAN2 - y_param not used

### ISSUE THREAD

**Issue by geraldvienna** [aidhound/hotxlfp#9]
In this line 
https://github.com/aidhound/hotxlfp/blob/master/hotxlfp/formulas/mathtrig.py#L145
there should be 
y_num = utils.parse_number(y_num)
but atm it is
y_num = utils.parse_number(x_num)

**Comment by leonelcamara** [comment]
This led me to find some errors in the testing of mathtrig. I'll fix it!

**Comment by leonelcamara** [comment]
@geraldvienna I released a new version with the fixes thanks a lot for your bug reporting.
